In [2]:
import numpy as np
x = np.array([10,20,30,40,50])
print(x)

[10 20 30 40 50]


In [6]:
X = np.array([[10,20,30],
             [15,25,25],
             [20,30,40],
             [25,35,45]])
print(X)
print("Shape: ", X.shape)

[[10 20 30]
 [15 25 25]
 [20 30 40]
 [25 35 45]]
Shape:  (4, 3)


In [8]:
X = np.random.randn(100,5)
print(X)
print("Shape: ", X.shape)

[[-6.05291574e-01  1.80890905e-01  1.72836673e+00  7.64393967e-01
  -6.52713732e-01]
 [ 3.27104593e-01  8.68318145e-01  1.98701100e-01 -1.45778085e+00
  -8.05244506e-01]
 [ 5.36557942e-01  1.93826600e-01  1.88086602e+00 -2.35650804e-03
  -5.18357531e-01]
 [ 7.41252698e-01 -4.57205534e-01  1.01877108e+00  1.11978828e-01
   1.19725255e+00]
 [ 1.48242537e+00  2.66660408e-01 -6.02160741e-01 -8.28142369e-01
   2.68639250e-01]
 [ 4.12607033e-01  1.04672949e+00 -1.10416738e+00  1.00096988e+00
  -1.06094198e+00]
 [-7.28906464e-01 -8.44184665e-01  4.50410002e-01 -3.83972937e-01
   1.54808200e+00]
 [-1.82503979e+00 -5.04987252e-01 -1.65271265e+00 -1.90883752e+00
  -3.26048101e-01]
 [-1.63418296e+00 -4.08031221e-01  9.32217964e-01 -2.01612749e+00
  -1.77225428e+00]
 [-5.57192149e-01 -3.83046408e-01  8.45164549e-01 -9.57674423e-01
  -1.73754531e+00]
 [ 3.55776173e-01  7.28468533e-02  8.22773551e-01  4.13308887e-01
   2.04419437e+00]
 [ 8.53496591e-01  5.87955939e-01 -1.27084666e+00  5.37690024e-01

In [ ]:
x = np.array([12,15,18,20,25,30,35])
print(np.mean(x))
print(np.median(x))
print(np.min(x))
print(np.max(x))

22.142857142857142


In [4]:
import numpy as np
x = np.array([12,15,18,20,25,30,35])
print("variance:" , np.var(x))
print("standard deviation:", np.std(x))
    

variance: 36.333333333333336
standard deviation: 6.027713773341708


In [7]:
x = np.array([10,20,30,40,50])
x_scaled = (x-np.min(x))/(np.max(x) - np.min(x))
print(x_scaled)

[0.   0.25 0.5  0.75 1.  ]


In [9]:
x = np.array([10, 20, 30, 40, 50])

z = (x - np.mean(x)) / np.std(x)

print(z)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [11]:
x = np.array([10, 20, np.nan, 40, 50, np.nan])

mean_value = np.nanmean(x)

x[np.isnan(x)] = mean_value

print(x)


[10. 20. 30. 40. 50. 30.]


In [12]:
x = np.array([10, 12, 11, 13, 12, 15, 100])

z = (x - np.mean(x)) / np.std(x)

outliers = x[np.abs(z) > 2]

print("Outliers:", outliers)

Outliers: [100]


In [13]:
X = np.random.randn(100, 4)
y = np.random.randint(0, 2, 100)

indices = np.random.permutation(len(X))

train_size = int(0.8 * len(X))

train_idx = indices[:train_size]
test_idx = indices[train_size:]

X_train = X[train_idx]
X_test = X[test_idx]

y_train = y[train_idx]
y_test = y[test_idx]

print(X_train.shape)
print(X_test.shape)


(80, 4)
(20, 4)


In [14]:
X = np.array([
    [1, 10],
    [2, 20],
    [3, 30],
    [4, 40],
    [5, 50]
])

np.random.shuffle(X)
print(X)


[[ 2 20]
 [ 4 40]
 [ 1 10]
 [ 5 50]
 [ 3 30]]


In [16]:
X = np.array([
    [25, 50000],
    [35, 70000],
    [45, 90000],
    [22, 30000],
    [50, 120000]
])

selected = X[X[:,1] > 60000]
print(selected)

[[    35  70000]
 [    45  90000]
 [    50 120000]]


In [17]:
y = np.array([0, 2, 1, 2, 0, 1])
one_hot = np.eye(3)[y]
print(one_hot)

[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [23]:
a = np.array([2, 3, 4])
b = np.array([5, 7, 9])

distance = np.sqrt(np.sum((a-b) ** 2))
print(distance)

7.0710678118654755


In [24]:
a = np.array([1, 2, 3])
b = np.array([2, 4, 6])
cosine_similarity = np.dot(a,b) / (np.linalg.norm(a)*np.linalg.norm(b))
print(cosine_similarity)

1.0


In [26]:
X = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

W = np.array([
    [0.1, 0.2],
    [0.3, 0.4],
    [0.5, 0.6]
])
# matrix multiplication
output = X@W
print(output)

[[2.2 2.8]
 [4.9 6.4]]


In [28]:
y_true = np.array([10, 20, 30, 40])
y_pred = np.array([12, 18, 33, 37])

# finding mean square error
mse = np.mean((y_true - y_pred) **2)
print(mse)

6.5


In [29]:
# pandas